/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.schema.tables.records;


import com.technokratos.model.jooq.schema.tables.Account;
import com.technokratos.model.jooq.schema.tables.pojos.AccountEntity;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountRecord extends UpdatableRecordImpl<AccountRecord> implements Record6<UUID, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.account.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.account.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.account.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.account.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.account.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.account.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.account.lastname</code>.
     */
    public void setLastname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.account.lastname</code>.
     */
    public String getLastname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.account.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.account.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.account.password</code>.
     */
    public void setPassword(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.account.password</code>.
     */
    public String getPassword() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Account.ACCOUNT_ENTITY.UUID;
    }

    @Override
    public Field<String> field2() {
        return Account.ACCOUNT_ENTITY.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return Account.ACCOUNT_ENTITY.NAME;
    }

    @Override
    public Field<String> field4() {
        return Account.ACCOUNT_ENTITY.LASTNAME;
    }

    @Override
    public Field<String> field5() {
        return Account.ACCOUNT_ENTITY.EMAIL;
    }

    @Override
    public Field<String> field6() {
        return Account.ACCOUNT_ENTITY.PASSWORD;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getLastname();
    }

    @Override
    public String component5() {
        return getEmail();
    }

    @Override
    public String component6() {
        return getPassword();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getLastname();
    }

    @Override
    public String value5() {
        return getEmail();
    }

    @Override
    public String value6() {
        return getPassword();
    }

    @Override
    public AccountRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public AccountRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public AccountRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public AccountRecord value4(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public AccountRecord value5(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public AccountRecord value6(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public AccountRecord values(UUID value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRecord
     */
    public AccountRecord() {
        super(Account.ACCOUNT_ENTITY);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(UUID uuid, String username, String name, String lastname, String email, String password) {
        super(Account.ACCOUNT_ENTITY);

        setUuid(uuid);
        setUsername(username);
        setName(name);
        setLastname(lastname);
        setEmail(email);
        setPassword(password);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(AccountEntity value) {
        super(Account.ACCOUNT_ENTITY);

        if (value != null) {
            setUuid(value.getUuid());
            setUsername(value.getUsername());
            setName(value.getName());
            setLastname(value.getLastname());
            setEmail(value.getEmail());
            setPassword(value.getPassword());
        }
    }
}
