/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.schema.tables.records;


import com.technokratos.model.jooq.schema.tables.Comment;
import com.technokratos.model.jooq.schema.tables.pojos.CommentEntity;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentRecord extends UpdatableRecordImpl<CommentRecord> implements Record4<UUID, UUID, UUID, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.comment.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.comment.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.comment.post_uuid</code>.
     */
    public void setPostUuid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.comment.post_uuid</code>.
     */
    public UUID getPostUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.comment.account_uuid</code>.
     */
    public void setAccountUuid(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.comment.account_uuid</code>.
     */
    public UUID getAccountUuid() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.comment.content</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.comment.content</code>.
     */
    public String getContent() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, UUID, UUID, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UUID, UUID, UUID, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Comment.COMMENT_ENTITY.UUID;
    }

    @Override
    public Field<UUID> field2() {
        return Comment.COMMENT_ENTITY.POST_UUID;
    }

    @Override
    public Field<UUID> field3() {
        return Comment.COMMENT_ENTITY.ACCOUNT_UUID;
    }

    @Override
    public Field<String> field4() {
        return Comment.COMMENT_ENTITY.CONTENT;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public UUID component2() {
        return getPostUuid();
    }

    @Override
    public UUID component3() {
        return getAccountUuid();
    }

    @Override
    public String component4() {
        return getContent();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public UUID value2() {
        return getPostUuid();
    }

    @Override
    public UUID value3() {
        return getAccountUuid();
    }

    @Override
    public String value4() {
        return getContent();
    }

    @Override
    public CommentRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public CommentRecord value2(UUID value) {
        setPostUuid(value);
        return this;
    }

    @Override
    public CommentRecord value3(UUID value) {
        setAccountUuid(value);
        return this;
    }

    @Override
    public CommentRecord value4(String value) {
        setContent(value);
        return this;
    }

    @Override
    public CommentRecord values(UUID value1, UUID value2, UUID value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommentRecord
     */
    public CommentRecord() {
        super(Comment.COMMENT_ENTITY);
    }

    /**
     * Create a detached, initialised CommentRecord
     */
    public CommentRecord(UUID uuid, UUID postUuid, UUID accountUuid, String content) {
        super(Comment.COMMENT_ENTITY);

        setUuid(uuid);
        setPostUuid(postUuid);
        setAccountUuid(accountUuid);
        setContent(content);
    }

    /**
     * Create a detached, initialised CommentRecord
     */
    public CommentRecord(CommentEntity value) {
        super(Comment.COMMENT_ENTITY);

        if (value != null) {
            setUuid(value.getUuid());
            setPostUuid(value.getPostUuid());
            setAccountUuid(value.getAccountUuid());
            setContent(value.getContent());
        }
    }
}
