/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.schema;


import com.technokratos.model.jooq.schema.tables.Account;
import com.technokratos.model.jooq.schema.tables.Comment;
import com.technokratos.model.jooq.schema.tables.Image;
import com.technokratos.model.jooq.schema.tables.Post;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account</code>.
     */
    public final Account ACCOUNT_ENTITY = Account.ACCOUNT_ENTITY;

    /**
     * The table <code>public.comment</code>.
     */
    public final Comment COMMENT_ENTITY = Comment.COMMENT_ENTITY;

    /**
     * The table <code>public.image</code>.
     */
    public final Image IMAGE_ENTITY = Image.IMAGE_ENTITY;

    /**
     * The table <code>public.post</code>.
     */
    public final Post POST_ENTITY = Post.POST_ENTITY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Account.ACCOUNT_ENTITY,
            Comment.COMMENT_ENTITY,
            Image.IMAGE_ENTITY,
            Post.POST_ENTITY
        );
    }
}
