/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.schema;


import com.technokratos.model.jooq.schema.tables.Account;
import com.technokratos.model.jooq.schema.tables.Comment;
import com.technokratos.model.jooq.schema.tables.Image;
import com.technokratos.model.jooq.schema.tables.Post;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT_ENTITY = Account.ACCOUNT_ENTITY;

    /**
     * The table <code>public.comment</code>.
     */
    public static final Comment COMMENT_ENTITY = Comment.COMMENT_ENTITY;

    /**
     * The table <code>public.image</code>.
     */
    public static final Image IMAGE_ENTITY = Image.IMAGE_ENTITY;

    /**
     * The table <code>public.post</code>.
     */
    public static final Post POST_ENTITY = Post.POST_ENTITY;
}
