/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.schema.tables.pojos;


import com.technokratos.model.Entity;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImageEntity extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID uuid;
    private UUID postUuid;
    private String imageUrl;

    public ImageEntity() {}

    public ImageEntity(ImageEntity value) {
        this.uuid = value.uuid;
        this.postUuid = value.postUuid;
        this.imageUrl = value.imageUrl;
    }

    public ImageEntity(
        UUID uuid,
        UUID postUuid,
        String imageUrl
    ) {
        this.uuid = uuid;
        this.postUuid = postUuid;
        this.imageUrl = imageUrl;
    }

    /**
     * Getter for <code>public.image.uuid</code>.
     */
    public UUID getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>public.image.uuid</code>.
     */
    public void setUuid(UUID uuid) {
        this.uuid = uuid;
    }

    /**
     * Getter for <code>public.image.post_uuid</code>.
     */
    public UUID getPostUuid() {
        return this.postUuid;
    }

    /**
     * Setter for <code>public.image.post_uuid</code>.
     */
    public void setPostUuid(UUID postUuid) {
        this.postUuid = postUuid;
    }

    /**
     * Getter for <code>public.image.image_url</code>.
     */
    public String getImageUrl() {
        return this.imageUrl;
    }

    /**
     * Setter for <code>public.image.image_url</code>.
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ImageEntity other = (ImageEntity) obj;
        if (this.uuid == null) {
            if (other.uuid != null)
                return false;
        }
        else if (!this.uuid.equals(other.uuid))
            return false;
        if (this.postUuid == null) {
            if (other.postUuid != null)
                return false;
        }
        else if (!this.postUuid.equals(other.postUuid))
            return false;
        if (this.imageUrl == null) {
            if (other.imageUrl != null)
                return false;
        }
        else if (!this.imageUrl.equals(other.imageUrl))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.uuid == null) ? 0 : this.uuid.hashCode());
        result = prime * result + ((this.postUuid == null) ? 0 : this.postUuid.hashCode());
        result = prime * result + ((this.imageUrl == null) ? 0 : this.imageUrl.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ImageEntity (");

        sb.append(uuid);
        sb.append(", ").append(postUuid);
        sb.append(", ").append(imageUrl);

        sb.append(")");
        return sb.toString();
    }
}
