/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.schema.tables.pojos;


import com.technokratos.model.Entity;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostEntity extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID uuid;
    private UUID authorUuid;
    private String title;
    private String content;

    public PostEntity() {}

    public PostEntity(PostEntity value) {
        this.uuid = value.uuid;
        this.authorUuid = value.authorUuid;
        this.title = value.title;
        this.content = value.content;
    }

    public PostEntity(
        UUID uuid,
        UUID authorUuid,
        String title,
        String content
    ) {
        this.uuid = uuid;
        this.authorUuid = authorUuid;
        this.title = title;
        this.content = content;
    }

    /**
     * Getter for <code>public.post.uuid</code>.
     */
    public UUID getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>public.post.uuid</code>.
     */
    public void setUuid(UUID uuid) {
        this.uuid = uuid;
    }

    /**
     * Getter for <code>public.post.author_uuid</code>.
     */
    public UUID getAuthorUuid() {
        return this.authorUuid;
    }

    /**
     * Setter for <code>public.post.author_uuid</code>.
     */
    public void setAuthorUuid(UUID authorUuid) {
        this.authorUuid = authorUuid;
    }

    /**
     * Getter for <code>public.post.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.post.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>public.post.content</code>.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>public.post.content</code>.
     */
    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PostEntity other = (PostEntity) obj;
        if (this.uuid == null) {
            if (other.uuid != null)
                return false;
        }
        else if (!this.uuid.equals(other.uuid))
            return false;
        if (this.authorUuid == null) {
            if (other.authorUuid != null)
                return false;
        }
        else if (!this.authorUuid.equals(other.authorUuid))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.content == null) {
            if (other.content != null)
                return false;
        }
        else if (!this.content.equals(other.content))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.uuid == null) ? 0 : this.uuid.hashCode());
        result = prime * result + ((this.authorUuid == null) ? 0 : this.authorUuid.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PostEntity (");

        sb.append(uuid);
        sb.append(", ").append(authorUuid);
        sb.append(", ").append(title);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }
}
